version: '3'

services:
  app:
    build: 
      context: ../..
      dockerfile: ./docker/dev/Dockerfile

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    depends_on:
      - app

volumes:
  dbdata: