version: '3'

services:
  app:
    build: 
      context: ../..
      dockerfile: ./docker/dev/Dockerfile

  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=cooking-masters
      - MYSQL_USER=quim
      - MYSQL_PASSWORD=barreiros
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    depends_on:
      - app

volumes:
  dbdata: